### ISSUE TITLE
Set up kanban borad

### ISSUE THREAD

**Issue by thecodechaser** [thecodechaser/Disney-characters-webapp#21]
### Hello there, The code reviewer 👋 
For this javascript capstone project, We are two students in the group. And we have removed all cards that were related to student c

**Comment by helman101** [comment]
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @thecodechaser  & @roshan-bajgain  👋, 

Good job so far with this project. 👏 👏👏
You've done well implementing some of the requirements, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [ ] You forgot to assing a member of the team to each task, kindly assign task to team member, when a task is assinged it should look like this:
![imagen](https://user-images.githubusercontent.com/60789317/146775546-f755707c-5ffd-4a30-81f6-a056f0b88ea4.png)
    - Kinldy remember to assing the task equaly
![imagen](https://user-images.githubusercontent.com/60789317/146775731-5053e3f9-3532-4834-b3ef-c5b50e75d98e.png)


Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by helman101** [comment]
# STATUS: APPROVED 🟢 🥳 

Hi @thecodechaser & @roshan-bajgain 🥇 , 

### Congratulations!!! 🥳 🎉

You have successfully completed all the expectations for this project, there is nothing more to do here, now you can go on your way and keep improving your skills.

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
